#!/usr/bin/env node
// Reads data/whatsapp.json and rewrites, in every page:
//   - <a data-wa="page">          → page message of that URL
//   - <a data-wa="service:KEY">   → service message KEY
//   - <input data-wa-fallback>    → value = page message (no-JS form)
//   - visible phone text          → "+595 992 279 599"
//   - tel: links and JSON-LD telephone → "+595992279599"
// and writes assets/js/wa-config.js for the quote form. Idempotent.
import fs from 'node:fs';
import path from 'node:path';
import { REPO_ROOT, sitemapPaths, fileForPath } from './lib.mjs';

const root = path.resolve(process.argv[2] || REPO_ROOT);
const map = JSON.parse(fs.readFileSync(path.join(root, 'data/whatsapp.json'), 'utf8'));
const { number, display, tel } = map;
const waHref = (text) => `https://wa.me/${number}?text=${encodeURIComponent(text)}`;
const escAttr = (s) => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;');
const serviceText = (k) => { const v = map.services[k]; return typeof v === 'string' ? v : v?.text; };

const paths = [...await sitemapPaths(root), '/404.html'];
let changed = 0; const problems = [];
for (const p of paths) {
  const f = fileForPath(root, p);
  if (!fs.existsSync(f)) continue;
  const before = fs.readFileSync(f, 'utf8');
  const pageText = map.pages[p]?.text;
  let html = before.replace(/<a\b[^>]*\bdata-wa="([^"]+)"[^>]*>/g, (tag, key) => {
    let text;
    if (key === 'page') text = pageText;
    else if (key.startsWith('service:')) text = serviceText(key.slice(8));
    if (!text) { problems.push(`${p}: no message for data-wa="${key}"`); return tag; }
    return /\bhref="[^"]*"/.test(tag) ? tag.replace(/\bhref="[^"]*"/, `href="${waHref(text)}"`) : tag.replace(/^<a\b/, `<a href="${waHref(text)}"`);
  });
  html = html.replace(/<input\b[^>]*\bdata-wa-fallback\b[^>]*>/g, (tag) => {
    if (!pageText) { problems.push(`${p}: fallback input but no page message`); return tag; }
    return tag.replace(/\bvalue="[^"]*"/, `value="${escAttr(pageText)}"`);
  });
  html = html
    .replace(/tel:\+?595[\s-]*992[\s-]*279[\s-]*599/g, `tel:${tel}`)
    .replace(/("telephone"\s*:\s*")[^"]*(")/g, `$1${tel}$2`)
    .replace(/\+595 992 279 ?599/g, display);
  if (html !== before) { fs.writeFileSync(f, html); changed++; }
}

const cfg = {
  number,
  display,
  tel,
  services: Object.fromEntries(Object.keys(map.services).map((k) => [k, serviceText(k)])),
  form: map.form || {},
};
const js = `// Generated by tools/apply-wa.mjs from data/whatsapp.json. Do not edit by hand.\nwindow.WA_CONFIG = ${JSON.stringify(cfg, null, 2)};\n`;
const cfgFile = path.join(root, 'assets/js/wa-config.js');
if (!fs.existsSync(cfgFile) || fs.readFileSync(cfgFile, 'utf8') !== js) { fs.writeFileSync(cfgFile, js); changed++; }

if (problems.length) { console.log(`apply-wa: problems\n  ${problems.join('\n  ')}`); process.exit(1); }
console.log(`apply-wa: ${changed} file(s) updated`);
